-- QUERY NAME: patch-index — MMS PRO patch list (reference only, do not run)
-- ══════════════════════════════════════════════════════════════
-- In Supabase SQL Editor: save/rename each query using the QUERY NAME line
-- from the matching file (first line of every supabase-patches/*.sql file).
-- ══════════════════════════════════════════════════════════════
--
-- APPLY ORDER (existing projects):
--   00-bootstrap.sql              → 00-bootstrap — Database bootstrap
--   01-fix-profiles.sql           → 01-fix-profiles — Backfill profiles
--   02-org-rls.sql                → 02-org-rls — Organization read policy
--   03-company-masters.sql        → 03-company-masters — Company masters
--   03-fix-user-signup-trigger.sql→ 03-fix-user-signup-trigger — Fix signup
--   04-org-assets-storage.sql     → 04-org-assets-storage — Org assets bucket
--   05-org-email-from-owner.sql   → 05-org-email-from-owner — Org email RPC
--   06-drop-department-code.sql   → 06-drop-department-code — Drop dept code
--   07-department-all-locations.sql → 07-department-all-locations
--   08-designations.sql           → 08-designations — Designations master
--   09-designation-departments.sql→ 09-designation-departments
--   10-org-employees.sql          → 10-org-employees — Employees master
--   11-employee-login.sql         → 11-employee-login — Employee login
--   12-employee-emails.sql        → 12-employee-emails — Additional emails
--   13-managers-department-heads-codes.sql → 13-managers-department-heads-codes
--   14-department-location-heads.sql → 14-department-location-heads
--   15-user-profile-fields.sql      → 15-user-profile-fields — Profile fields
--   16-user-assets-storage.sql      → 16-user-assets-storage — User avatars
--   17-asset-fields.sql             → 17-asset-fields — Asset field definitions
--   18-asset-field-dropdown.sql     → 18-asset-field-dropdown — Dropdown type
--   19-manual-work-orders.sql       → 19-manual-work-orders — Manual WO form
--   20-work-order-assets-storage.sql → 20-work-order-assets-storage — WO files bucket
--   21-work-order-assignment.sql      → 21-work-order-assignment — Employee assignment
--   22-work-order-multi-assignees.sql → 22-work-order-multi-assignees — Multiple assignees
--   23-org-limits.sql               → 23-org-limits — Organization resource limits
--   24-asset-field-dependencies.sql → 24-asset-field-dependencies — Conditional parent fields
--   25-asset-section-icons.sql      → 25-asset-section-icons — Section PNG/SVG icons
--   26-location-heads.sql           → 26-location-heads — Location head employee
--   27-performance-indexes.sql      → 27-performance-indexes — Performance indexes
--   28-org-access-roles.sql         → 28-org-access-roles — Custom access roles
--   29-account-roles.sql            → 29-account-roles — Super Admin / Admin / User
--   30-access-roles-all-locations.sql → 30-access-roles-all-locations — Roles org-wide
--   31-seed-location-head-role.sql  → 31-seed-location-head-role — Location Head template
--   32-expand-access-module-keys.sql → 32-expand-access-module-keys — Split module permissions
--   33-access-roles-created-by.sql  → 33-access-roles-created-by — Role creator ownership
--   34-location-head-roles-access.sql → 34-location-head-roles-access — LH Roles & Access
--   35-org-assets-employee-photos.sql → 35-org-assets-employee-photos — Employee photo uploads
--   36-work-order-department-assignment.sql → 36-work-order-department-assignment — Dept WO assignment
--   37-work-order-assignment-cascade.sql → 37-work-order-assignment-cascade — Location-only cascade (includes 36 cols)
--   38-equipment-inventory.sql          → 38-equipment-inventory — Areas + equipment + dynamic fields
--   39-drop-designations-department-heads.sql → 39-drop-designations-department-heads — Remove designation + dept head
--   40-field-required.sql                 → 40-field-required — Required field flag
--   41-field-type-radio.sql             → 41-field-type-radio — Radio field type
--   42-equipment-share-asset-sections.sql → 42-equipment-share-asset-sections
--   43-equipment-dynamic-identity.sql   → 43-equipment-dynamic-identity
--   44-work-requests.sql                → 44-work-requests — Work request module
--   45-work-request-draft-number.sql    → 45-work-request-draft-number — Draft WR numbers
--   46-work-request-form-field-values.sql → 46-work-request-form-field-values — WR form values
--   47-approve-permissions.sql          → 47-approve-permissions — WR/WO approve permissions
--   48-warranty-tasks-permissions.sql   → 48-warranty-tasks-permissions — Warranty & tasks modules
--   49-warranty-manager.sql             → 49-warranty-manager — Warranty records and line items
--   50-vendor-master.sql                → 50-vendor-master — Vendor master records
--   51-warranty-vendor-link.sql         → 51-warranty-vendor-link — Warranty vendor FK
--   52-warranty-serial-format.sql        → 52-warranty-serial-format — WM/YYYY/0000 S.No.
--   53-task-management.sql               → 53-task-management — Task Management module
--   54-task-meta-descriptions.sql          → 54-task-meta-descriptions — Status/priority descriptions
--   55-warranty-documents.sql              → 55-warranty-documents — Warranty document attachments
--   56-org-assets-warranty-documents.sql     → 56-org-assets-warranty-documents — PDF/docs in org-assets
--   57-performance-indexes-2.sql             → 57-performance-indexes-2 — Additional performance indexes
--   58-trigram-search-indexes.sql            → 58-trigram-search-indexes — Trigram indexes for search
--   59-task-spec-compliance.sql              → 59-task-spec-compliance — Task spec fields & masters
--   60-task-performance.sql                  → 60-task-performance — Task indexes & counts RPC
--   61-work-order-wr-spec-compliance.sql      → 61-work-order-wr-spec-compliance — WR/WO CMMS lifecycle
--   62-performance-indexes-3.sql               → 62-performance-indexes-3 — List/query covering indexes
--   63-dashboard-stats.sql                      → 63-dashboard-stats — Work order dashboard aggregations RPC
--   64-user-notifications.sql                   → 64-user-notifications — In-app notification inbox
--   65-planned-maintenance.sql                    → 65-planned-maintenance — Planned Maintenance & Scheduled WOs
--   66-work-request-short-description.sql         → 66-work-request-short-description — WR/WO short description
--   67-department-head-approval.sql               → 67-department-head-approval — DH approval & role assignment
--   68-work-centers.sql                           → 68-work-centers — Work center master
--   69-work-request-job-nature.sql                  → 69-work-request-job-nature — WR job nature
--   70-work-order-permit-details.sql                → 70-work-order-permit-details — Per-type WO permits
--   71-work-order-daily-logs.sql                    → 71-work-order-daily-logs — WO daily work logs
--   72-list-visibility-rpcs.sql                     → 72-list-visibility-rpcs — Paginated received-WO visibility RPCs
--   73-org-statuses.sql                             → 73-org-statuses — Configurable status masters
--   74-checklist-sections.sql                       → 74-checklist-sections — Checklist template sections
--   75-pm-schedule-reading.sql                        → 75-pm-schedule-reading — PM calendar units & reading fields

--   76-pm-plan-overdue-status.sql                     → 76-pm-plan-overdue-status — Overdue status for PM plans
--   77-report-schedules.sql                           → 77-report-schedules — Scheduled report email delivery

--
-- OTHER:
--   supabase.sql                  → supabase — Full schema (new projects)
--   supabase-dashboard.sql        → supabase-dashboard — Plants/work orders fix
--   99-wipe-all.sql               → 99-wipe-all — Full wipe (destructive)
--
-- RENAME EXISTING "Untitled query" ENTRIES:
--   Open each saved query → click the title → paste the QUERY NAME from its file.

select 'MMS PRO patch index — reference only' as info;
